language: node_js

node_js:
  - 'node'
  - '8.11'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

before_script:
  - yarn global add gulp-cli

script: gulp

cache: yarn

before_deploy: 'rm -R node_modules'

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: leapdao.org
  acl: public_read
  local_dir: '.'
  skip_cleanup: true
  region: 'eu-west-1'

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_1 --paths "/*"
  - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID_2 --paths "/*"
