language: generic
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: leapdao.org
  acl: public_read
  local_dir: '.'
  skip_cleanup: true
  region: 'eu-west-1'
